apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: aws-dkp-admin-aws-dkp
spec:
  destination:
    namespace: default
    server: https://aws-dkp-apiserver-714779767.us-west-2.elb.amazonaws.com:6443
  project: default
  source:
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/abcodefresh/*.yaml,runtimes/abcodefresh/**/*.yaml}'
      recurse: true
    path: resources
    repoURL: https://github.com/arvindbhoj/cf-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
